config/routes.rb
Rails.application.routes.draw do
  
  resources :alls
  resources :posts
  resources :tests
  resources :buildings

    get '/listings', to: 'listings#index'
    post 'listings', to: 'listings#create'
    get '/listings/new', to: 'listings#new', as: :new_listing
    get 'listings/:id/edit', to: 'listings#edit', as: 'edit_listing'
    get 'listings/:id', to: 'listings#show', as: 'listing'
    patch 'listings/:id', to: 'listings#update'
    put 'listings/:id', to: 'listings#update'
    delete 'listings/:id', to: 'listings#destroy'

    get '/properties/bootstrap', to: 'properties#bootstrap', as: :properties_bootstrap

end

app/models/all.rb
class All < ActiveRecord::Base
  belongs_to :listing
end

app/controllers/alls_controller.rb
class AllsController < ApplicationController
  before_action :set_all, only: [:show, :edit, :update, :destroy]

  # GET /alls
  # GET /alls.json
  def index
    @alls = All.all
  end

  # GET /alls/1
  # GET /alls/1.json
  def show
  end

  # GET /alls/new
  def new
    @all = All.new
  end

  # GET /alls/1/edit
  def edit
  end

  # POST /alls
  # POST /alls.json
  def create
    @all = All.new(all_params)

    respond_to do |format|
      if @all.save
        format.html { redirect_to @all, notice: 'All was successfully created.' }
        format.json { render :show, status: :created, location: @all }
      else
        format.html { render :new }
        format.json { render json: @all.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alls/1
  # PATCH/PUT /alls/1.json
  def update
    respond_to do |format|
      if @all.update(all_params)
        format.html { redirect_to @all, notice: 'All was successfully updated.' }
        format.json { render :show, status: :ok, location: @all }
      else
        format.html { render :edit }
        format.json { render json: @all.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alls/1
  # DELETE /alls/1.json
  def destroy
    @all.destroy
    respond_to do |format|
      format.html { redirect_to alls_url, notice: 'All was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_all
      @all = All.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def all_params
      params.require(:all).permit(:one, :two, :three, :four, :five, :six, :seven, :listing_id, :nine, :ten, :eleven, :twelve, :thirteen, :fourteen, :fifteen, :sixteen, :seventeen, :eighteen, :nineteen)
    end
end

app/helpers/alls_helper.rb
module AllsHelper
end

app/views/alls/_form.html.erb
<%= form_for(@all) do |f| %>
  <% if @all.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@all.errors.count, "error") %> prohibited this all from being saved:</h2>

      <ul>
      <% @all.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :one %><br>
    <%= f.text_field :one %>
  </div>
  <div class="field">
    <%= f.label :two %><br>
    <%= f.check_box :two %>
  </div>
  <div class="field">
    <%= f.label :three %><br>
    <%= f.date_select :three %>
  </div>
  <div class="field">
    <%= f.label :four %><br>
    <%= f.datetime_select :four %>
  </div>
  <div class="field">
    <%= f.label :five %><br>
    <%= f.text_field :five %>
  </div>
  <div class="field">
    <%= f.label :six %><br>
    <%= f.text_field :six %>
  </div>
  <div class="field">
    <%= f.label :seven %><br>
    <%= f.number_field :seven %>
  </div>
  <div class="field">
    <%= f.label :listing_id %><br>
    <%= f.text_field :listing_id %>
  </div>
  <div class="field">
    <%= f.label :nine %><br>
    <%= f.text_field :nine %>
  </div>
  <div class="field">
    <%= f.label :ten %><br>
    <%= f.text_area :ten %>
  </div>
  <div class="field">
    <%= f.label :eleven %><br>
    <%= f.time_select :eleven %>
  </div>
  <div class="field">
    <%= f.label :twelve %><br>
    <%= f.datetime_select :twelve %>
  </div>
  <div class="field">
    <%= f.label :thirteen %><br>
    <%= f.text_field :thirteen %>
  </div>
  <div class="field">
    <%= f.label :fourteen %><br>
    <%= f.text_field :fourteen %>
  </div>
  <div class="field">
    <%= f.label :fifteen %><br>
    <%= f.text_field :fifteen %>
  </div>
  <div class="field">
    <%= f.label :sixteen %><br>
    <%= f.text_field :sixteen %>
  </div>
  <div class="field">
    <%= f.label :seventeen %><br>
    <%= f.text_field :seventeen %>
  </div>
  <div class="field">
    <%= f.label :eighteen %><br>
    <%= f.text_field :eighteen %>
  </div>
  <div class="field">
    <%= f.label :nineteen %><br>
    <%= f.text_field :nineteen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alls/edit.html.erb
<h1>Editing All</h1>

<%= render 'form' %>

<%= link_to 'Show', @all %> |
<%= link_to 'Back', alls_path %>

app/views/alls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alls</h1>

<table>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Listing</th>
      <th>Nine</th>
      <th>Ten</th>
      <th>Eleven</th>
      <th>Twelve</th>
      <th>Thirteen</th>
      <th>Fourteen</th>
      <th>Fifteen</th>
      <th>Sixteen</th>
      <th>Seventeen</th>
      <th>Eighteen</th>
      <th>Nineteen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alls.each do |all| %>
      <tr>
        <td><%= all.one %></td>
        <td><%= all.two %></td>
        <td><%= all.three %></td>
        <td><%= all.four %></td>
        <td><%= all.five %></td>
        <td><%= all.six %></td>
        <td><%= all.seven %></td>
        <td><%= all.listing %></td>
        <td><%= all.nine %></td>
        <td><%= all.ten %></td>
        <td><%= all.eleven %></td>
        <td><%= all.twelve %></td>
        <td><%= all.thirteen %></td>
        <td><%= all.fourteen %></td>
        <td><%= all.fifteen %></td>
        <td><%= all.sixteen %></td>
        <td><%= all.seventeen %></td>
        <td><%= all.eighteen %></td>
        <td><%= all.nineteen %></td>
        <td><%= link_to 'Show', all %></td>
        <td><%= link_to 'Edit', edit_all_path(all) %></td>
        <td><%= link_to 'Destroy', all, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New All', new_all_path %>

app/views/alls/new.html.erb
<h1>New All</h1>

<%= render 'form' %>

<%= link_to 'Back', alls_path %>

app/views/alls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>One:</strong>
  <%= @all.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @all.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @all.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @all.four %>
</p>

<p>
  <strong>Five:</strong>
  <%= @all.five %>
</p>

<p>
  <strong>Six:</strong>
  <%= @all.six %>
</p>

<p>
  <strong>Seven:</strong>
  <%= @all.seven %>
</p>

<p>
  <strong>Listing:</strong>
  <%= @all.listing %>
</p>

<p>
  <strong>Nine:</strong>
  <%= @all.nine %>
</p>

<p>
  <strong>Ten:</strong>
  <%= @all.ten %>
</p>

<p>
  <strong>Eleven:</strong>
  <%= @all.eleven %>
</p>

<p>
  <strong>Twelve:</strong>
  <%= @all.twelve %>
</p>

<p>
  <strong>Thirteen:</strong>
  <%= @all.thirteen %>
</p>

<p>
  <strong>Fourteen:</strong>
  <%= @all.fourteen %>
</p>

<p>
  <strong>Fifteen:</strong>
  <%= @all.fifteen %>
</p>

<p>
  <strong>Sixteen:</strong>
  <%= @all.sixteen %>
</p>

<p>
  <strong>Seventeen:</strong>
  <%= @all.seventeen %>
</p>

<p>
  <strong>Eighteen:</strong>
  <%= @all.eighteen %>
</p>

<p>
  <strong>Nineteen:</strong>
  <%= @all.nineteen %>
</p>

<%= link_to 'Edit', edit_all_path(@all) %> |
<%= link_to 'Back', alls_path %>