config/routes.rb
Rails.application.routes.draw do
  
  resources :alls
  resources :posts
  resources :tests
  resources :buildings

    get '/listings', to: 'listings#index'
    post 'listings', to: 'listings#create'
    get '/listings/new', to: 'listings#new', as: :new_listing
    get 'listings/:id/edit', to: 'listings#edit', as: 'edit_listing'
    get 'listings/:id', to: 'listings#show', as: 'listing'
    patch 'listings/:id', to: 'listings#update'
    put 'listings/:id', to: 'listings#update'
    delete 'listings/:id', to: 'listings#destroy'

    get '/properties/bootstrap', to: 'properties#bootstrap', as: :properties_bootstrap

end

app/models/building.rb
class Building < ActiveRecord::Base
  def some_code_here
    puts "some code here"
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.fetch(:building, {})
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buildings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>